apiVersion: v1
kind: Service
metadata:
  name: pod-monitor-api
  namespace: pod-monitor
  labels:
    app: pod-monitor
    component: api
spec:
  type: ClusterIP
  selector:
    app: pod-monitor
    component: api
  ports:
    - port: 80
      targetPort: 5001
      protocol: TCP
      name: http
