---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-monitor-config
  namespace: pod-monitor
data:
  AWS_REGION: "eu-west-2"
  ENVIRONMENT: "dev"
  FLASK_PORT: "5001"
  FLASK_DEBUG: "0"
  AUDIO_BUCKET: "pod-monitor-audio-dev"
  DATA_BUCKET: "pod-monitor-data-dev"
  PODCASTS_TABLE: "pod-monitor-dev-podcasts"
  EPISODES_TABLE: "pod-monitor-dev-episodes"
  DISTRIBUTION_TABLE: "pod-monitor-dev-distribution-lists"
  BEDROCK_MODEL_ID: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  SENDER_EMAIL: "pod-monitor@bmj.com"
