apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pod-monitor

bases:
  - ../../base

images:
  - name: "REPLACE_ECR_URL"
    newName: "REPLACE_WITH_ECR_REPO_URL"
    newTag: "latest"

patches:
  - path: env-patch.yaml
  - path: serviceaccount-patch.yaml
  - path: replicas-patch.yaml
