apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: editor-prompt-tool
  # namespace: nextjs
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/load-balancer-name: k8s-editor-prompt-tool
    alb.ingress.kubernetes.io/certificate-arn: 
    alb.ingress.kubernetes.io/target-type: ip
    # external-dns.alpha.kubernetes.io/hostname: moved to service-patch
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 15
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 20
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600,load_balancing.algorithm.type=least_outstanding_requests
    alb.ingress.kubernetes.io/inbound-cidrs: 
    alb.ingress.kubernetes.io/tags: app=editor-prompt-tool,Project=editor-prompt,CostCentre=bestpractice
    alb.ingress.kubernetes.io/group.name: editor-prompt-tool
  labels:
    app: editor-prompt-tool
spec:
  ingressClassName: alb
  rules: