apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: nextjs

commonLabels:
  app.kubernetes.io/name: editor-prompt-tool
  app: editor-prompt-tool
  team: platform
  CostCentre: bestpractice
  project: editor-prompt
  product: editor-prompt
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - ingress.yaml
  - instrumentation.yaml
  - job.yaml
